exports.SESSION_SECRET = process.env.SESSION_SECRET;
exports.GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
exports.GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
exports.GOOGLE_SSO_URL = process.env.GOOGLE_SSO_URL;
exports.DB_PASSWORD = process.env.DB_PASSWORD;
exports.DB_USERNAME = process.env.DB_USERNAME;
exports.DB_URL = process.env.DB_URL.replace(
  '<username>',
  this.DB_USERNAME
).replace('<password>', this.DB_PASSWORD);

exports.GOOGLE_CRET =
  '-----BEGIN CERTIFICATE-----\n' +
  'MIIDdDCCAlygAwIBAgIGAXgXPcYnMA0GCSqGSIb3DQEBCwUAMHsxFDASBgNVBAoTC0dvb2dsZSBJ\n' +
  'bmMuMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MQ8wDQYDVQQDEwZHb29nbGUxGDAWBgNVBAsTD0dv\n' +
  'b2dsZSBGb3IgV29yazELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWEwHhcNMjEwMzA5\n' +
  'MTM0NzA2WhcNMjYwMzA4MTM0NzA2WjB7MRQwEgYDVQQKEwtHb29nbGUgSW5jLjEWMBQGA1UEBxMN\n' +
  'TW91bnRhaW4gVmlldzEPMA0GA1UEAxMGR29vZ2xlMRgwFgYDVQQLEw9Hb29nbGUgRm9yIFdvcmsx\n' +
  'CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A\n' +
  'MIIBCgKCAQEAjtE6YbaoaDfzdbHVmnL8oWiZRNGmB60sxx1h3f7spSMmjFG3FoMPzhLDtUUMfkhe\n' +
  'FR1wKdisGvr68JtwrU0dfhr3j99bhOye/lbVRvKlBHbP5z8nPi5AhNcIQf+CxGScOQR3dbeVdaqd\n' +
  'DEo71ghPWHOM50c/Sp72BJ3aRQyLH3SCUXhL8tZmTmdKvUBwrzUCyJtk9+gMospKFn/fUNW97hmk\n' +
  'gP2q5zhIovP0zw8YANGzfi9oi7qW3dGn9X6Qnr25U2SMKvw8BcQ95ctASBkAXvsbUHx9n7LYVcaA\n' +
  '665oI3JTrIOgddi5bbzMF0UtLa8yKI1KZ1zleoOy24f6wIt6kQIDAQABMA0GCSqGSIb3DQEBCwUA\n' +
  'A4IBAQAE5boASr9rYzpijb5nENAlFm9Y5FevJRKB4wj2QIDgAyI+vZOze+s3XJMXZG9LPFKu7Nyq\n' +
  'QZAVig0v9z3vRGo+FAVzoBOkTcx3oHZLIPp0Rz8mQhqH7Li7bH2VBChC7xZII0Lq6QA1fwG0m3ZX\n' +
  'AluIKiDVrnP/QnRWSrpMkGFCRVCK1zQALM6U7Gy0voT9HYYz1Ktp7J128GFQ6nIIpEMp+RvWjnd7\n' +
  'rAxbbKpbF0MXFOeO+1dHVTN9+AWJmp7NF4HxHFnN8TWb046YAa7Tgtc4mNbyUfTXUVPfEuvNmwBB\n' +
  '+kpxTqb3VeV3JFTMT6iGoddbUIfY57wu+xP7vvUhpxRx\n' +
  '-----END CERTIFICATE-----';

exports.CLIENT_SUCCESS_URL = `${process.env.CLIENT_URL}/profile`;
exports.CLIENT_FAILURE_URL = `${process.env.CLIENT_URL}/login`;
exports.SERVER_URL = process.env.SERVER_URL;
exports.JWT_SECRET = process.env.JWT_SECRET;
